name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
        ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Check formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          skip-commit: true
          version: "1.22.0"
      - name: Print bad formatting
        run: git --no-pager diff --exit-code
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test